# Generated by Django 4.0.2 on 2022-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('ogrn', models.CharField(max_length=13)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=9)),
                ('post_address', models.CharField(max_length=255)),
            ],
        ),
    ]
