# Generated by Django 4.0.2 on 2022-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(default='sdfsdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='university',
            name='inn',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='kpp',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='ogrn',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='post_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
