# Generated by Django 4.0.2 on 2022-02-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_university_name_alter_university_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
