# Generated by Django 4.0.2 on 2022-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_university_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unexplored'), (1, 'No Data'), (2, 'Indexed')], default=0),
        ),
    ]
