# Generated by Django 4.0.2 on 2022-02-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_university_latitude_university_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(max_length=1024, unique=True)),
                ('amount', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='main.university')),
            ],
        ),
    ]
