# Generated by Django 4.0.2 on 2022-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='identifier',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
