# Generated by Django 4.0.2 on 2022-02-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_purchase_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(max_length=1024),
        ),
    ]
