# Generated by Django 4.0.2 on 2022-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_university_rating_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(default='', max_length=255),
        ),
    ]
